// Generated by scripts/fetch-photos.mjs — do not edit by hand.
// Real dish photography from TheMealDB, resolved once and baked in so the app
// has no runtime dependency on an image API.

export const PHOTOS: Record<string, string[]> = {
  "tacos": [
    "https://www.themealdb.com/images/media/meals/dk70uv1784670127.jpg",
    "https://www.themealdb.com/images/media/meals/uvuyxu1503067369.jpg",
    "https://www.themealdb.com/images/media/meals/ypxvwv1505333929.jpg"
  ],
  "burrito": [
    "https://www.themealdb.com/images/media/meals/prrirc1763781360.jpg",
    "https://www.themealdb.com/images/media/meals/swo87v1763595282.jpg",
    "https://www.themealdb.com/images/media/meals/qqpwsy1511796276.jpg",
    "https://www.themealdb.com/images/media/meals/jyylmo1763790808.jpg"
  ],
  "quesadilla": [
    "https://www.themealdb.com/images/media/meals/oal8x31764119345.jpg",
    "https://www.themealdb.com/images/media/meals/7i6csk1780094394.jpg",
    "https://www.themealdb.com/images/media/meals/wurrux1468416624.jpg",
    "https://www.themealdb.com/images/media/meals/swttys1511385853.jpg",
    "https://www.themealdb.com/images/media/meals/sxwquu1511793428.jpg",
    "https://www.themealdb.com/images/media/meals/wpkfin1763597958.jpg"
  ],
  "elote": [
    "https://www.themealdb.com/images/media/meals/vz94r81760534692.jpg",
    "https://www.themealdb.com/images/media/meals/xb97a81583266727.jpg",
    "https://www.themealdb.com/images/media/meals/yf5eyw1783804464.jpg",
    "https://www.themealdb.com/images/media/meals/smoa3h1762341142.jpg",
    "https://www.themealdb.com/images/media/meals/sng9bm1765320170.jpg",
    "https://www.themealdb.com/images/media/meals/0h1b7m1764120235.jpg"
  ],
  "chips": [
    "https://www.themealdb.com/images/media/meals/j223gc1784579841.jpg"
  ],
  "horchata": [
    "https://www.themealdb.com/images/media/meals/pjbaq11784731571.jpg"
  ],
  "lemonade": [
    "https://www.themealdb.com/images/media/meals/rjhf741585564676.jpg",
    "https://www.themealdb.com/images/media/meals/e756bf1761848342.jpg",
    "https://www.themealdb.com/images/media/meals/ntafxw1763586291.jpg",
    "https://www.themealdb.com/images/media/meals/4hzyvq1763792564.jpg",
    "https://www.themealdb.com/images/media/meals/w36ets1764362474.jpg"
  ],
  "bao": [
    "https://www.themealdb.com/images/media/meals/vqpwrv1511723001.jpg",
    "https://www.themealdb.com/images/media/meals/as88dq1762772486.jpg",
    "https://www.themealdb.com/images/media/meals/tzt3it1764363293.jpg",
    "https://www.themealdb.com/images/media/meals/l6hj9a1784668199.jpg",
    "https://www.themealdb.com/images/media/meals/tzsy461763769901.jpg",
    "https://www.themealdb.com/images/media/meals/08c5f41764791918.jpg"
  ],
  "dumplings": [
    "https://www.themealdb.com/images/media/meals/uyqrrv1511553350.jpg",
    "https://www.themealdb.com/images/media/meals/jbw8m11780155348.jpg",
    "https://www.themealdb.com/images/media/meals/sfahy01763752319.jpg",
    "https://www.themealdb.com/images/media/meals/oemdp11779556068.jpg",
    "https://www.themealdb.com/images/media/meals/dd7t4d1764877271.jpg",
    "https://www.themealdb.com/images/media/meals/tsdbcq1764795636.jpg"
  ],
  "ramen": [
    "https://www.themealdb.com/images/media/meals/zry07j1763779321.jpg",
    "https://www.themealdb.com/images/media/meals/ikizdm1763760862.jpg",
    "https://www.themealdb.com/images/media/meals/prrirc1763781360.jpg",
    "https://www.themealdb.com/images/media/meals/118oj61763423896.jpg",
    "https://www.themealdb.com/images/media/meals/6g3rso1763486069.jpg",
    "https://www.themealdb.com/images/media/meals/rvypwy1503069308.jpg"
  ],
  "pho": [
    "https://www.themealdb.com/images/media/meals/x2fw9e1560460636.jpg",
    "https://www.themealdb.com/images/media/meals/sqpqtp1515365614.jpg",
    "https://www.themealdb.com/images/media/meals/1529446137.jpg",
    "https://www.themealdb.com/images/media/meals/xxtsvx1511814083.jpg",
    "https://www.themealdb.com/images/media/meals/x0mreq1784577446.jpg",
    "https://www.themealdb.com/images/media/meals/7n8su21699013057.jpg"
  ],
  "banhmi": [
    "https://www.themealdb.com/images/media/meals/djdg8l1784578885.jpg",
    "https://www.themealdb.com/images/media/meals/j80gmw1764372176.jpg",
    "https://www.themealdb.com/images/media/meals/xr0n4r1576788363.jpg",
    "https://www.themealdb.com/images/media/meals/sbx7n71587673021.jpg",
    "https://www.themealdb.com/images/media/meals/xutquv1505330523.jpg",
    "https://www.themealdb.com/images/media/meals/wooxjq1784663522.jpg"
  ],
  "springrolls": [
    "https://www.themealdb.com/images/media/meals/6ebldy1784672108.jpg",
    "https://www.themealdb.com/images/media/meals/grhn401765687086.jpg",
    "https://www.themealdb.com/images/media/meals/u9l7k81628771647.jpg",
    "https://www.themealdb.com/images/media/meals/txce0y1782494894.jpg",
    "https://www.themealdb.com/images/media/meals/q8sp3j1593349686.jpg",
    "https://www.themealdb.com/images/media/meals/9r2xrg1763771238.jpg"
  ],
  "wings": [
    "https://www.themealdb.com/images/media/meals/feh9k21784665694.jpg",
    "https://www.themealdb.com/images/media/meals/4hzyvq1763792564.jpg"
  ],
  "tea": [
    "https://www.themealdb.com/images/media/meals/vussxq1511882648.jpg",
    "https://www.themealdb.com/images/media/meals/tqtywx1468317395.jpg",
    "https://www.themealdb.com/images/media/meals/qysyss1511558054.jpg",
    "https://www.themealdb.com/images/media/meals/yx8j1i1763484612.jpg",
    "https://www.themealdb.com/images/media/meals/paejva1765321314.jpg",
    "https://www.themealdb.com/images/media/meals/st9shl1763755808.jpg"
  ],
  "burger": [
    "https://www.themealdb.com/images/media/meals/lgmnff1763789847.jpg",
    "https://www.themealdb.com/images/media/meals/44bzep1761848278.jpg",
    "https://www.themealdb.com/images/media/meals/k420tj1585565244.jpg",
    "https://www.themealdb.com/images/media/meals/vdwloy1713225718.jpg"
  ],
  "fries": [
    "https://www.themealdb.com/images/media/meals/j223gc1784579841.jpg"
  ],
  "onionrings": [
    "https://www.themealdb.com/images/media/meals/ppodrp1762325183.jpg",
    "https://www.themealdb.com/images/media/meals/xvrrux1511783685.jpg",
    "https://www.themealdb.com/images/media/meals/1c5oso1614347493.jpg",
    "https://www.themealdb.com/images/media/meals/dbazbg1763779999.jpg",
    "https://www.themealdb.com/images/media/meals/tqd7s21763780609.jpg",
    "https://www.themealdb.com/images/media/meals/0bpjb11763075817.jpg"
  ],
  "milkshake": [
    "https://www.themealdb.com/images/media/meals/1xscby1764790242.jpg",
    "https://www.themealdb.com/images/media/meals/s9qyzd1764790772.jpg",
    "https://www.themealdb.com/images/media/meals/9kecho1784575366.jpg"
  ],
  "salad": [
    "https://www.themealdb.com/images/media/meals/7ytdtz1784833420.jpg",
    "https://www.themealdb.com/images/media/meals/bqx8mc1782684286.jpg",
    "https://www.themealdb.com/images/media/meals/ji3mho1782499823.jpg",
    "https://www.themealdb.com/images/media/meals/zry07j1763779321.jpg",
    "https://www.themealdb.com/images/media/meals/fqpqml1764359125.jpg",
    "https://www.themealdb.com/images/media/meals/z458v91763817681.jpg"
  ],
  "shawarma": [
    "https://www.themealdb.com/images/media/meals/kcv6hj1598733479.jpg",
    "https://www.themealdb.com/images/media/meals/i8l2fu1763742525.jpg",
    "https://www.themealdb.com/images/media/meals/swo87v1763595282.jpg",
    "https://www.themealdb.com/images/media/meals/hcg6l91763596970.jpg"
  ],
  "hummus": [
    "https://www.themealdb.com/images/media/meals/gpon5u1763801180.jpg",
    "https://www.themealdb.com/images/media/meals/zub3s91764110535.jpg"
  ],
  "kebab": [
    "https://www.themealdb.com/images/media/meals/04axct1763793018.jpg",
    "https://www.themealdb.com/images/media/meals/prjve31763486864.jpg"
  ],
  "pita": [
    "https://www.themealdb.com/images/media/meals/u5e9qq1763795441.jpg",
    "https://www.themealdb.com/images/media/meals/ae6clc1760524712.jpg"
  ],
  "pizza": [
    "https://www.themealdb.com/images/media/meals/lrfdwz1764438393.jpg",
    "https://www.themealdb.com/images/media/meals/wf49qs1763075222.jpg",
    "https://www.themealdb.com/images/media/meals/x0lk931587671540.jpg"
  ],
  "garlicbread": [
    "https://www.themealdb.com/images/media/meals/lmc6r51764365554.jpg",
    "https://www.themealdb.com/images/media/meals/54xzk31760524666.jpg",
    "https://www.themealdb.com/images/media/meals/fnfnhi1784671116.jpg",
    "https://www.themealdb.com/images/media/meals/hqaejl1695738653.jpg",
    "https://www.themealdb.com/images/media/meals/i8l2fu1763742525.jpg",
    "https://www.themealdb.com/images/media/meals/hem6gk1784664868.jpg"
  ],
  "cheese": [
    "https://www.themealdb.com/images/media/meals/oal8x31764119345.jpg",
    "https://www.themealdb.com/images/media/meals/7i6csk1780094394.jpg",
    "https://www.themealdb.com/images/media/meals/wurrux1468416624.jpg",
    "https://www.themealdb.com/images/media/meals/swttys1511385853.jpg",
    "https://www.themealdb.com/images/media/meals/sxwquu1511793428.jpg",
    "https://www.themealdb.com/images/media/meals/wpkfin1763597958.jpg"
  ],
  "steak": [
    "https://www.themealdb.com/images/media/meals/vussxq1511882648.jpg",
    "https://www.themealdb.com/images/media/meals/qysyss1511558054.jpg",
    "https://www.themealdb.com/images/media/meals/st9shl1763755808.jpg",
    "https://www.themealdb.com/images/media/meals/lmwaf61783805434.jpg"
  ],
  "chicken": [
    "https://www.themealdb.com/images/media/meals/wyxwsp1486979827.jpg",
    "https://www.themealdb.com/images/media/meals/er4d081765186828.jpg",
    "https://www.themealdb.com/images/media/meals/cj56fs1762340001.jpg",
    "https://www.themealdb.com/images/media/meals/1529446352.jpg",
    "https://www.themealdb.com/images/media/meals/tyywsw1505930373.jpg",
    "https://www.themealdb.com/images/media/meals/qpxvuq1511798906.jpg"
  ],
  "sandwich": [
    "https://www.themealdb.com/images/media/meals/djdg8l1784578885.jpg",
    "https://www.themealdb.com/images/media/meals/j80gmw1764372176.jpg",
    "https://www.themealdb.com/images/media/meals/xr0n4r1576788363.jpg",
    "https://www.themealdb.com/images/media/meals/sbx7n71587673021.jpg",
    "https://www.themealdb.com/images/media/meals/xutquv1505330523.jpg",
    "https://www.themealdb.com/images/media/meals/wooxjq1784663522.jpg"
  ],
  "cucumber": [
    "https://www.themealdb.com/images/media/meals/7ytdtz1784833420.jpg",
    "https://www.themealdb.com/images/media/meals/bqx8mc1782684286.jpg",
    "https://www.themealdb.com/images/media/meals/ji3mho1782499823.jpg",
    "https://www.themealdb.com/images/media/meals/zry07j1763779321.jpg",
    "https://www.themealdb.com/images/media/meals/fqpqml1764359125.jpg",
    "https://www.themealdb.com/images/media/meals/z458v91763817681.jpg"
  ],
  "restaurant": [
    "https://www.themealdb.com/images/media/meals/sxxpst1468569714.jpg",
    "https://www.themealdb.com/images/media/meals/mlkjeu1782775816.jpg",
    "https://www.themealdb.com/images/media/meals/k07k271782502861.jpg",
    "https://www.themealdb.com/images/media/meals/uyqrrv1511553350.jpg",
    "https://www.themealdb.com/images/media/meals/sypxpx1515365095.jpg",
    "https://www.themealdb.com/images/media/meals/tnwy8m1628770384.jpg"
  ],
  "food": [
    "https://www.themealdb.com/images/media/meals/wyxwsp1486979827.jpg",
    "https://www.themealdb.com/images/media/meals/er4d081765186828.jpg",
    "https://www.themealdb.com/images/media/meals/cj56fs1762340001.jpg",
    "https://www.themealdb.com/images/media/meals/1529446352.jpg",
    "https://www.themealdb.com/images/media/meals/tyywsw1505930373.jpg",
    "https://www.themealdb.com/images/media/meals/qpxvuq1511798906.jpg"
  ]
};
