/**
 * Resolves one real food photo per keyword from TheMealDB and writes a static
 * map to src/lib/photos.ts. Run once; the app then has zero runtime dependency
 * on an image API, and every photo is guaranteed to be food.
 *
 *   node scripts/fetch-photos.mjs
 */
import { writeFileSync } from "node:fs";

const API = "https://www.themealdb.com/api/json/v1/1";

// keyword -> search terms to try, in order. First hit wins.
const WANTED = {
  tacos: ["taco"],
  burrito: ["burrito", "wrap"],
  quesadilla: ["quesadilla", "cheese"],
  elote: ["corn", "sweetcorn"],
  chips: ["nachos", "fries"],
  horchata: ["milkshake", "smoothie"],
  lemonade: ["lemon"],
  bao: ["bun", "pork"],
  dumplings: ["dumpling"],
  ramen: ["noodle"],
  pho: ["soup", "pho"],
  banhmi: ["sandwich", "baguette"],
  springrolls: ["spring roll", "roll"],
  wings: ["wings", "chicken"],
  coffee: ["coffee", "tiramisu"],
  tea: ["tea", "cake"],
  burger: ["burger"],
  fries: ["fries", "potato"],
  onionrings: ["onion"],
  milkshake: ["milkshake", "ice cream"],
  salad: ["salad"],
  shawarma: ["shawarma", "kebab"],
  hummus: ["hummus", "dip"],
  kebab: ["kebab", "koshari"],
  pita: ["falafel", "flatbread"],
  pizza: ["pizza"],
  garlicbread: ["garlic bread", "bread"],
  cheese: ["cheese"],
  steak: ["steak", "beef"],
  chicken: ["chicken"],
  sandwich: ["sandwich"],
  cucumber: ["salad", "cucumber"],
  restaurant: ["stew", "curry"],
  food: ["chicken"],
};

async function search(term) {
  const res = await fetch(`${API}/search.php?s=${encodeURIComponent(term)}`);
  if (!res.ok) return [];
  const data = await res.json();
  return (data.meals ?? []).map((m) => ({ name: m.strMeal, thumb: m.strMealThumb }));
}

const out = {};
const report = [];

for (const [key, terms] of Object.entries(WANTED)) {
  let hits = [];
  for (const t of terms) {
    hits = await search(t);
    if (hits.length > 0) break;
  }
  if (hits.length === 0) {
    report.push(`  MISS  ${key}`);
    continue;
  }
  // Keep several so different dishes sharing a keyword get different photos.
  out[key] = hits.slice(0, 6).map((h) => h.thumb);
  report.push(`  ok    ${key.padEnd(13)} ${hits.length} photo(s) — e.g. ${hits[0].name}`);
}

const file = `// Generated by scripts/fetch-photos.mjs — do not edit by hand.
// Real dish photography from TheMealDB, resolved once and baked in so the app
// has no runtime dependency on an image API.

export const PHOTOS: Record<string, string[]> = ${JSON.stringify(out, null, 2)};
`;

writeFileSync("src/lib/photos.ts", file);
console.log(report.join("\n"));
console.log(`\nWrote src/lib/photos.ts — ${Object.keys(out).length} keywords, ${Object.values(out).flat().length} photos.`);
